name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: 1enzz
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publicar animação no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
